pipeline {
    agent any

    environment {
        // Add the GITHUB credentials
        GIT_CREDENTIALS_ID = 'GIHUB_CREDS'
        REPO_URL = 'https://github.com/mwunnam/messaging_app.git'
        git branch = 'main'
    }

    stages {
        stage('Clone Repository') {
            step {
                git credentialsId: "${GIT_CREDENTIALS_ID}", url: "${REPO_URL}" 
            }
        }

        stage('Install Dependenies') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip3 install --upgrade pip'
                sh '. venv/bin/activate && pip3 install -r messaging_app/requirements.txt'
                sh '. pip install flake8'

            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest --junitxml=pytest-report.xml
                '''
            }
        }

        stage('Test Report') {
            steps {
                junit 'pytest-report.xml'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'pytest-report.xml', allowEmptyArchive: true
        }

        failure {
            echo 'Build failed, Please check the test report for more info'
        }

        success {
            echo 'Build and Test was successful'
        }
    }
}
